version: '3.9'

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - pth-data:/var/lib/postgresql/data

volumes:
  pth-data:
    driver: local

