name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_PASSWORD: ci
      DATABASE_URL: postgres://postgres:ci@localhost:5432/postgres?sslmode=disable
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19
    - name: Install dependencies
      run: |
        go get .
    - name: Build
      run: go build -v ./...
