name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19
    - name: Install dependencies
      run: |
        go get .
    - name: Build
      run: go build -v ./...
    - name: Test
      run: |
       make migration_up 
       go test -v ./...
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable
